# Generated by Django 2.2.1 on 2022-03-24 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat1', models.CharField(max_length=500)),
                ('stat2', models.CharField(max_length=500)),
                ('stat3', models.CharField(max_length=500)),
                ('stat4', models.CharField(max_length=500)),
                ('stat5', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='shipment',
            name='statuses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Status1'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
